### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by jchan-scc** [acstevens/ctakes-standalone-application#1]
Hi 

I am getting compilation error,  I have java 8.  Any ideas?  Thanks, Joyce

---

ERROR] /Users/jchan-scc/vagrant_boxes/ubuntu_trusty/ctakes-standalone-application/src/main/java/com/sentimetrix/ctakes/service/ClinicalEntityRecognizer.java:[18,35] cannot find symbol
  symbol:   class IdentifiedAnnotationUtil
  location: package org.apache.ctakes.core.util
[ERROR] /Users/jchan-scc/vagrant_boxes/ubuntu_trusty/ctakes-standalone-application/src/main/java/com/sentimetrix/ctakes/service/ClinicalEntityRecognizer.java:[168,62] cannot find symbol
  symbol:   variable IdentifiedAnnotationUtil
  location: class com.sentimetrix.ctakes.service.ClinicalEntityRecognizer

**Comment by acstevens** [comment]
fixed with commit on Dec 15, 2015.
