### ISSUE TITLE
startup.bat not exist

### ISSUE THREAD

**Issue by mso1830** [acstevens/ctakes-standalone-application#2]
I followed your instruction and built the app. however, I cannot find the startup.bat in the "target\ctakes-standalone-application-0.0.1-SNAPSHOT-bin\ctakes-standalone-application-0.0.1-SNAPSHOT".

can you help me to run the application on my end

**Comment by acstevens** [comment]
I just went through the steps again myself and ran into no problems.  I am wondering if the build failed for you?  Did the mvn command result in any errors?

Here are the results of my build.

```
> ls -1
ctakes-standalone-application-0.0.1-SNAPSHOT.jar
lib
org
startup.bat
startup.sh
```

**Comment by mso1830** [comment]
I think the problem is in the git clone command which results in the following:
` C:\Users\MSO>git clone https://github.com/acstevens/ctakes-standalone-application  
Cloning into 'ctakes-standalone-application'...  
 remote: Counting objects: 482, done.                                                                                                  

Receiving objects: 100% (482/482), 91.69 MiB | 43.78 MiB/s, done.  
Resolving deltas: 100% (73/73), done.  
Checking connectivity... done.  
git-lfs smudge -- 'src/main/resources/org/apache/ctakes/dictionary/lookup/orange_book_hsqldb/umls.backup': git-lfs: command not found 
error: external filter git-lfs smudge -- %f failed -1  
error: external filter git-lfs smudge -- %f failed  
fatal: src/main/resources/org/apache/ctakes/dictionary/lookup/orange_book_hsqldb/umls.backup: smudge filter lfs failed  
warning: Clone succeeded, but checkout failed.  
You can inspect what was checked out with 'git status'  
and retry the checkout with 'git checkout -f HEAD'  
                                                                                                                                      `

the *.backup and *.data are uploaded using git lfs.
Therefore,  I followed the instructions to install git lfs from here:[https://help.github.com/articles/installing-git-large-file-storage/](url).
Then I configure my git lfs to associate with *.backup and *.data by following this link:
[https://help.github.com/articles/configuring-git-large-file-storage/](url).

nonetheless, I then used Git shell instead of using the windows command prompt.

The problem is solved and I was able to clone and build the app. However, I am not sure whether the problem is solved by installing the git lfs or by using the git shell instead of windows command prompt.

**Comment by acstevens** [comment]
thanks for the note.  i'll update to instructions to point out the need for git-lfs.
